//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TJQ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airlines
    {
        public decimal AirlineID { get; set; }
        public string AirlineNumber { get; set; }
        public string AirlineCode { get; set; }
        public string AirlineName { get; set; }
        public bool VATExempt { get; set; }
        public bool PSTExempt { get; set; }
        public string Province { get; set; }
        public bool Preferred { get; set; }
    }
}
