//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TJQ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class APInvoices
    {
        public decimal InvoiceID { get; set; }
        public decimal ARInvoiceID { get; set; }
        public decimal ARInvoiceDetailID { get; set; }
        public string InvoiceNumber { get; set; }
        public short BranchNumber { get; set; }
        public string ProfileNumber { get; set; }
        public string ProfileName { get; set; }
        public string ProfileAddress { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> SystemDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int PostingMonth { get; set; }
        public string Description { get; set; }
        public decimal InvoiceAmount { get; set; }
        public decimal VatAmount { get; set; }
        public decimal PstAmount { get; set; }
        public decimal Balance { get; set; }
        public string CurrencyCode { get; set; }
        public string VatCode { get; set; }
        public double ExchangeRate { get; set; }
        public string PayableAccount { get; set; }
        public bool OnHold { get; set; }
        public bool MarkToPay { get; set; }
        public decimal AmountToPay { get; set; }
        public decimal AddedBy { get; set; }
        public string Remarks { get; set; }
        public string TicketNumber { get; set; }
        public string InvoiceGroup { get; set; }
    }
}
