//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TJQ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARInvoiceBalances
    {
        public decimal InvoiceBalanceID { get; set; }
        public decimal InvoiceID { get; set; }
        public decimal InvoiceAmount { get; set; }
        public decimal VatAmount { get; set; }
        public decimal PstAmount { get; set; }
        public decimal Balance { get; set; }
        public string CurrencyCode { get; set; }
        public double ExchangeRate { get; set; }
        public string ReceivableAccount { get; set; }
    }
}
