//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TJQ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARInvoices
    {
        public decimal InvoiceID { get; set; }
        public string InvoiceNumber { get; set; }
        public short BranchNumber { get; set; }
        public int IataNumber { get; set; }
        public string Division { get; set; }
        public string ProfileNumber { get; set; }
        public string ProfileName { get; set; }
        public string ProfileAddress { get; set; }
        public string ProfileEmail { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> SystemDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Description { get; set; }
        public string BookingAgentNumber { get; set; }
        public string TicketingAgentNumber { get; set; }
        public string OSAgentNumber1 { get; set; }
        public string OSAgentNumber2 { get; set; }
        public string RecordLocator { get; set; }
        public string InvoiceGroup { get; set; }
        public string VatCode { get; set; }
        public short Status { get; set; }
        public decimal AddedBy { get; set; }
        public string InvoiceRemarks { get; set; }
        public string PrivateRemarks { get; set; }
    }
}
