//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TJQ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IfInvoiceDetails
    {
        public decimal InvoiceDetailID { get; set; }
        public decimal InvoiceID { get; set; }
        public decimal ReservationID { get; set; }
        public byte TransactionType { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public decimal PostingMonth { get; set; }
        public byte SubmitTo { get; set; }
        public string VendorNumber { get; set; }
        public string VendorName { get; set; }
        public string VendorAddress { get; set; }
        public string VendorPhone { get; set; }
        public string VendorFax { get; set; }
        public string VendorEmail { get; set; }
        public string ChainCode { get; set; }
        public string PropertyCode { get; set; }
        public string CommissionClientNumber { get; set; }
        public string AgencyCCVendorNumber { get; set; }
        public string AgencyCCCardNumber { get; set; }
        public byte ProductCode { get; set; }
        public string VatCode { get; set; }
        public string CurrencyCode { get; set; }
        public string PassengerName { get; set; }
        public string ValidatingCarrier { get; set; }
        public string TicketNumber { get; set; }
        public bool ETicket { get; set; }
        public bool Exchange { get; set; }
        public bool ADM { get; set; }
        public string OriginalTicket { get; set; }
        public string OriginalInvoice { get; set; }
        public decimal PublishedFare { get; set; }
        public decimal SellingFare { get; set; }
        public decimal ReferenceFare { get; set; }
        public decimal LowFare { get; set; }
        public decimal Tax1 { get; set; }
        public decimal Tax2 { get; set; }
        public decimal Tax3 { get; set; }
        public decimal Tax4 { get; set; }
        public decimal Penalty { get; set; }
        public decimal GrossAmount { get; set; }
        public decimal CommissionAmount { get; set; }
        public decimal VatOnCommission { get; set; }
        public decimal PstOnCommission { get; set; }
        public decimal PenaltyCommission { get; set; }
        public decimal NetFare { get; set; }
        public string NetFareValueCode { get; set; }
        public decimal BookingAgentCommission { get; set; }
        public decimal TicketingAgentCommission { get; set; }
        public decimal OSAgentCommission1 { get; set; }
        public decimal OSAgentCommission2 { get; set; }
        public bool International { get; set; }
        public string ExceptionCode { get; set; }
        public string GSANumber { get; set; }
        public string PurchaseOrder { get; set; }
        public string FreeFieldA { get; set; }
        public string FreeFieldB { get; set; }
        public string FreeFieldC { get; set; }
        public string FreeFieldD { get; set; }
        public string RoutingCode { get; set; }
        public string TourCode { get; set; }
        public string GroupCode { get; set; }
        public string TransactionCode { get; set; }
        public string Source { get; set; }
        public Nullable<System.DateTime> TravelDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public short NumberOfDays { get; set; }
        public short NumberOfPassengers { get; set; }
        public short NumberOfItems { get; set; }
        public string ItemType { get; set; }
        public string CityCode { get; set; }
        public decimal VoucherRate { get; set; }
        public byte RateType { get; set; }
        public byte Status { get; set; }
        public byte VoucherStatus { get; set; }
        public Nullable<System.DateTime> APDueDate { get; set; }
        public decimal AddedBy { get; set; }
    }
}
