//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TJQ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IfPayments
    {
        public decimal PaymentID { get; set; }
        public decimal InvoiceDetailID { get; set; }
        public byte FormOfPayment { get; set; }
        public string AccountNumber { get; set; }
        public string BankNumber { get; set; }
        public decimal CCID { get; set; }
        public string Reference { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string CardHolder { get; set; }
        public string AuthorizationNumber { get; set; }
        public decimal Amount { get; set; }
        public string CurrencyCode { get; set; }
    }
}
