//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TJQ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Segments
    {
        public decimal SegmentID { get; set; }
        public decimal InvoiceID { get; set; }
        public decimal InvoiceDetailID { get; set; }
        public byte LegNumber { get; set; }
        public string DepartureCityCode { get; set; }
        public Nullable<System.DateTime> DepartureInfo { get; set; }
        public string ArrivalCityCode { get; set; }
        public Nullable<System.DateTime> ArrivalInfo { get; set; }
        public string AirlineCode { get; set; }
        public string FlightNumber { get; set; }
        public string ClassOfService { get; set; }
        public string XO { get; set; }
        public string DI { get; set; }
        public string FareBasis { get; set; }
        public decimal LegPrice { get; set; }
        public int Mileage { get; set; }
    }
}
